// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SecureMailAnalyzer.Api.Data;

#nullable disable

namespace SecureMailAnalyzer.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714150014_AddUsersAndUserId")]
    partial class AddUsersAndUserId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SecureMailAnalyzer.Api.Models.Analysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DetectedSignals")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detected_signals");

                    b.Property<string>("EducationalExplanation")
                        .HasColumnType("text")
                        .HasColumnName("educational_explanation");

                    b.Property<string>("InputContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input_content");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input_type");

                    b.Property<string>("LlmAssessment")
                        .HasColumnType("text")
                        .HasColumnName("llm_assessment");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("risk_level");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("risk_score");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("analyses", (string)null);
                });

            modelBuilder.Entity("SecureMailAnalyzer.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
